# Generated by Django 4.2 on 2024-04-14 14:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exchange",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.UUID("e9a2e44a-e593-4d53-a91e-cb6abceb3a88"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, verbose_name="Название Биржы"),
                ),
                (
                    "location",
                    models.CharField(max_length=250, verbose_name="Адрес биржы"),
                ),
                ("trade_volume", models.FloatField(verbose_name="Объем торгов")),
            ],
            options={
                "verbose_name": "Биржа",
                "verbose_name_plural": "Биржи",
            },
        ),
    ]
