# Generated by Django 4.2 on 2024-04-15 19:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("site_crypto", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assets",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.UUID("cdd00322-da50-4f4d-a136-25c5501f3560"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, verbose_name="Название Биржы"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("cryptocurrency", "Cryptocurrency"),
                            ("fiat", "Fiat"),
                        ],
                        max_length=20,
                        verbose_name="Тип актива",
                    ),
                ),
                ("price", models.FloatField(verbose_name="Стоимость актива")),
            ],
            options={
                "verbose_name": "Активы",
            },
        ),
        migrations.AlterField(
            model_name="exchange",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("cde09643-7fae-4423-a247-61eb2f78e2eb"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.CreateModel(
            name="Deals",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.UUID("77b1601f-69e8-4346-90a7-23b955762193"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("buying", models.FloatField(verbose_name="Цена покупки")),
                ("selling", models.FloatField(verbose_name="Цена продажи")),
                ("profit", models.TimeField(verbose_name="Прибыль")),
                ("time", models.TimeField(verbose_name="Время сделки")),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="site_crypto.assets",
                    ),
                ),
                (
                    "buying_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buying_deals",
                        to="site_crypto.exchange",
                    ),
                ),
                (
                    "selling_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selling_deals",
                        to="site_crypto.exchange",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сделки",
            },
        ),
    ]
