# Generated by Django 4.2 on 2024-04-21 13:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("site_crypto", "0002_assets_alter_exchange_uuid_deals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assets",
            name="type",
            field=models.CharField(
                choices=[("cryptocurrency", "Cryptocurrency"), ("fiat", "Fiat")],
                verbose_name="Тип актива",
            ),
        ),
        migrations.AlterField(
            model_name="assets",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("902378c5-941e-4f91-85e0-be1856e461d7"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="deals",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("cc6232b5-c92d-4bc2-8bf2-ca5ebb755027"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="exchange",
            name="uuid",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
