# Generated by Django 4.2 on 2024-04-21 13:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "site_crypto",
            "0003_alter_assets_type_alter_assets_uuid_alter_deals_uuid_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="assets",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("b19aa81d-5b83-44fa-98d9-6ad2109a3d11"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="deals",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("9cea13d1-193d-4160-a70d-063361229e96"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="exchange",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
