# Generated by Django 4.2 on 2024-04-21 13:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("site_crypto", "0004_alter_assets_uuid_alter_deals_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assets",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="deals",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
